// Code generated by mockery v2.41.0. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/WalterPaes/go-rest-api-crud/internal/domain"
	mock "github.com/stretchr/testify/mock"

	resterrors "github.com/WalterPaes/go-rest-api-crud/pkg/rest_errors"
)

// LoginService is an autogenerated mock type for the LoginService type
type LoginService struct {
	mock.Mock
}

// LoginUser provides a mock function with given fields: ctx, user
func (_m *LoginService) LoginUser(ctx context.Context, user *domain.User) (string, *resterrors.RestErr) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for LoginUser")
	}

	var r0 string
	var r1 *resterrors.RestErr
	if rf, ok := ret.Get(0).(func(context.Context, *domain.User) (string, *resterrors.RestErr)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.User) string); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.User) *resterrors.RestErr); ok {
		r1 = rf(ctx, user)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*resterrors.RestErr)
		}
	}

	return r0, r1
}

// NewLoginService creates a new instance of LoginService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLoginService(t interface {
	mock.TestingT
	Cleanup(func())
}) *LoginService {
	mock := &LoginService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
